# Generated by Django 2.2 on 2020-03-04 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChattingBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='om', max_length=120, verbose_name='Your Name')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Of Birth')),
            ],
        ),
    ]
